name: Deploy website
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  test:
    env:
      name: ${{secrets.Name}}
      date: 01-021009
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: get name
        run: |
           echo "${{env.name}}"
           echo "${{env.date}}"
      - name: cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: dependency-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish-json.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependency-cache-${{ hashFiles('**/package-lock.json') }} 
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: publish json
        id: publish-json
        run: find dist -type f -name "*.json" -execdir echo 'script-file={}' >>$GITHUB_OUTPUT ';'
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: List files
        run: ls -lrt
      - name: Read script file
        run: echo '${{ needs.build.outputs.script-file }}'
      - name: Deploy
        run: echo "Deploying..."
